name: learn-github-actions
on: [push]
jobs:
  spdx-sbom-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pwd
      - run: ls -la
      - name: Install spdx-sbom-generator
        run: |
          sudo apt-get install -y wget
          wget https://github.com/spdx/spdx-sbom-generator/releases/download/v0.0.10/spdx-sbom-generator-v0.0.10-linux-amd64.tar.gz -O generator.tar.gz
          tar -zxf generator.tar.gz
          ./spdx-sbom-generator -h

  # publish-spdx-file:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-java@v1
  #     with:
  #       java-version: '11.0.13'
  #   - name: Create spdx-file
  #     id: spdx-builder
  #     uses: philips-software/spdx-action@v0.9.1.1
  #     with:
  #       project: go-experiments
  #       mode: ort
  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: licenses
  #       path: ${{ steps.spdx-builder.outputs.spdx-file }}
