name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  publish-spdx-file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.0.13'
    - name: Create spdx-file
      id: spdx-builder
      uses: philips-software/spdx-action@v0.9.1.1
      with:
        project: github.com/leoluz/go-experiments
        mode: ort
    - uses: actions/upload-artifact@v2
      with:
        name: licenses
        path: ${{ steps.spdx-builder.outputs.spdx-file }}
