name: learn-github-actions
on: [push]
jobs:
  spdx-sbom-generator:
    runs-on: ubuntu-latest
    env:
      spdxGeneratorVersion: v0.0.13
      gomodFolder: .
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Generate SBOM (spdx)
        id: spdx-builder
        run: |
          wget -q https://github.com/opensbom-generator/spdx-sbom-generator/releases/download/$spdxGeneratorVersion/spdx-sbom-generator-$spdxGeneratorVersion-linux-386.tar.gz -O generator.tar.gz
          tar -zxf generator.tar.gz
          if [[ ! -z $gomodFolder ]]; then
            ./spdx-sbom-generator $gomodFolder -o /tmp
          fi
          if [[ ! -z $uiFolder ]]; then
            yarn install --cwd $uiFolder
            ./spdx-sbom-generator -p $uiFolder -o /tmp
          fi
      - uses: actions/upload-artifact@v2
        with:
          name: licenses
          path: /tmp/*.spdx
