name: learn-github-actions
on: [push]
jobs:
  spdx-sbom-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.17.2
      - name: Define target version
        run: |
          TARGET_VERSION=latest
          echo "TARGET_VERSION=${TARGET_VERSION}" >> $GITHUB_ENV
      - name: Generate SBOM (spdx)
        id: spdx-builder
        env:
          SPDX_GEN_VERSION: v0.0.13
          SIGS_BOM_VERSION: v0.2.1
          PROJECT_FOLDERS: ".,./ui" 
          DOCKER_IMAGE: argoproj/argocd:${{ env.TARGET_VERSION }}
        run: |
          yarn install --cwd ./ui

          go install sigs.k8s.io/bom/cmd/bom@$SIGS_BOM_VERSION
          go install github.com/spdx/spdx-sbom-generator/cmd/generator@SPDX_GEN_VERSION

          # Generate SPDX for project dependencies analyzing package managers
          for folder in $(echo $PROJECT_FOLDERS | sed "s/,/ /g")
          do
            generator -p $folder -o /tmp
          done

          # Generate SPDX for binaries analyzing the docker image
          if [[ ! -z $DOCKER_IMAGE ]]; then
            bom generate -o /tmp/bom-docker-image.spdx -i $DOCKER_IMAGE
          fi

          tar -zcf /tmp/sbom.tar.gz /tmp/*.spdx
      - uses: actions/upload-artifact@v2
        with:
          name: sbom
          path: /tmp/sbom.tar.gz
